// <auto-generated />
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260624215801_AdimnRelationShip")]
    partial class AdimnRelationShip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Classes.Property", b =>
                {
                    b.Property<int>("ProperyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProperyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManageAdminUsserId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOFRooms")
                        .HasColumnType("int");

                    b.Property<int>("RentPrice")
                        .HasColumnType("int");

                    b.HasKey("ProperyID");

                    b.HasIndex("ManageAdminUsserId");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.User", b =>
                {
                    b.Property<int>("UsserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("adminUsserId")
                        .HasColumnType("int");

                    b.HasKey("UsserId");

                    b.HasIndex("adminUsserId");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Admin", b =>
                {
                    b.HasBaseType("DataAccessLayer.Classes.User");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Property", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Admin", "ManageAdmin")
                        .WithMany("Properties")
                        .HasForeignKey("ManageAdminUsserId");

                    b.Navigation("ManageAdmin");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.User", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Admin", "admin")
                        .WithMany("Users")
                        .HasForeignKey("adminUsserId");

                    b.Navigation("admin");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Admin", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("DataAccessLayer.Classes.Admin", "UsserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Admin", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
