// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260625115647_Updates")]
    partial class Updates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Classes.Message", b =>
                {
                    b.Property<int>("MessageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Isdeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OwnerUsserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReciveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderFlag")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time")
                        .HasComputedColumnSql("DATEDIFF(SECOND, [ReciveDate], [ReadDate]) / 3600.0", true);

                    b.Property<int>("tentantUsserId")
                        .HasColumnType("int");

                    b.HasKey("MessageID");

                    b.HasIndex("OwnerUsserId");

                    b.HasIndex("tentantUsserId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Property", b =>
                {
                    b.Property<int>("ProperyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProperyID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManageAdminUsserId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOFRooms")
                        .HasColumnType("int");

                    b.Property<int>("OwnerUsserId")
                        .HasColumnType("int");

                    b.Property<int>("RentPrice")
                        .HasColumnType("int");

                    b.HasKey("ProperyID");

                    b.HasIndex("ManageAdminUsserId");

                    b.HasIndex("OwnerUsserId");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceID");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.User", b =>
                {
                    b.Property<int>("UsserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("adminUsserId")
                        .HasColumnType("int");

                    b.HasKey("UsserId");

                    b.HasIndex("adminUsserId");

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DataAccessLayer.ModelContetxt.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReciveDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReiewerUsserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewdPropertyProperyID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimewStamp")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("time")
                        .HasComputedColumnSql("DATEDIFF(SECOND, [ReciveDate], [ReadDate]) / 3600.0", true);

                    b.HasKey("ReviewID");

                    b.HasIndex("ReiewerUsserId");

                    b.HasIndex("ReviewdPropertyProperyID");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("PropertyService", b =>
                {
                    b.Property<int>("PropertiesProperyID")
                        .HasColumnType("int");

                    b.Property<int>("ServicesServiceID")
                        .HasColumnType("int");

                    b.HasKey("PropertiesProperyID", "ServicesServiceID");

                    b.HasIndex("ServicesServiceID");

                    b.ToTable("PropertyService");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Admin", b =>
                {
                    b.HasBaseType("DataAccessLayer.Classes.User");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Owner", b =>
                {
                    b.HasBaseType("DataAccessLayer.Classes.User");

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Tentant", b =>
                {
                    b.HasBaseType("DataAccessLayer.Classes.User");

                    b.ToTable("Tentant");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Message", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Owner", "Owner")
                        .WithMany("Messages")
                        .HasForeignKey("OwnerUsserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Classes.Tentant", "tentant")
                        .WithMany("Messages")
                        .HasForeignKey("tentantUsserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("tentant");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Property", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Admin", "ManageAdmin")
                        .WithMany("Properties")
                        .HasForeignKey("ManageAdminUsserId");

                    b.HasOne("DataAccessLayer.Classes.Owner", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerUsserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManageAdmin");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.User", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Admin", "admin")
                        .WithMany("Users")
                        .HasForeignKey("adminUsserId");

                    b.Navigation("admin");
                });

            modelBuilder.Entity("DataAccessLayer.ModelContetxt.Review", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Tentant", "Reiewer")
                        .WithMany("Reviews")
                        .HasForeignKey("ReiewerUsserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Classes.Property", "ReviewdProperty")
                        .WithMany("Reviews")
                        .HasForeignKey("ReviewdPropertyProperyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reiewer");

                    b.Navigation("ReviewdProperty");
                });

            modelBuilder.Entity("PropertyService", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertiesProperyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Classes.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Admin", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("DataAccessLayer.Classes.Admin", "UsserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Owner", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("DataAccessLayer.Classes.Owner", "UsserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Tentant", b =>
                {
                    b.HasOne("DataAccessLayer.Classes.User", null)
                        .WithOne()
                        .HasForeignKey("DataAccessLayer.Classes.Tentant", "UsserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Property", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Admin", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Owner", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("DataAccessLayer.Classes.Tentant", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
